require('plugins.config.nvim-treesitter')
require('plugins.config.nvim-lspconfig')
require('plugins.config.nvim-cmp')
require('plugins.config.fzf-lua')
-- Trying fzf-lua
-- require('plugins.config.telescope')
require('plugins.config.lualine')
require('plugins.config.nvim-tree')
require('plugins.config.gitsigns')
require('plugins.config.auto-session')
