require('plugins.config.nvim-treesitter')
require('plugins.config.nvim-lsp-installer')
require('plugins.config.nvim-lspconfig')
require('plugins.config.nvim-cmp')
require('plugins.config.telescope')
require('plugins.config.lualine')
require('plugins.config.nvim-tree')